apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stocker
  namespace: m2-red-mockers
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stocker
    spec:
      containers:
      - name: stocker
        image: ffdcdevuksouth.azurecr.io/red.mockers/stocker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 512Mi
      imagePullSecrets:
      - name: microservice-regsecret
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-stocker
  namespace: m2-red-mockers
  labels:
    app: stocker
spec:
  ports:
  - port: 80
  selector:
    app: stocker
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: microservice-stocker
  namespace: m2-red-mockers
  labels:
    type: http
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/hostname: stocker-red-mockers-m2.qa.ffdc.tradingbell.men
    external-dns.alpha.kubernetes.io/target: ingress-controller.qa.ffdc.tradingbell.men
spec:
  rules:
  - host: stocker-red-mockers-m2.qa.ffdc.tradingbell.men
    http:
      paths:
      - backend:
          serviceName: microservice-stocker
          servicePort: 80
